### ISSUE TITLE
Is more different from concrete 5.7 version?

### ISSUE THREAD

**Issue by tkart38** [Kaapiii/concrete5_doctrine_dql_extensions#1]
hi
a simple question, a version of this package for concrete5.7 are more different?
I'm working with c5 5.7 and need to add the MATCH_AGAINST extension for doctrine , but i dont' know how can add this extension.
thanks in advances
bye

**Comment by Kaapiii** [comment]
Hi @tkart38

**Plugin**
Concrete5 version 7 uses many EntityManager instances at the same time. There is created an instance for the Core, the application classes and even for each installed package. Since this solution gave some flexibility, there are two main disadvantages. It's very inefficient and a nightmare for handling/accessing core entities in packages. 

This changed in concrete5 version 8. Now there is only one EntityManager per database connection. So the Core, the application and by default all packages use the same EntityManager instance. That's why the plugin only works for version 8 and higher.

**Solution**
Even though it's possible to add a MATCH_AGAINST extension for doctrine.

1. Make sure that concrete5 only runs with one EntityManager instance. (Override at least 3 Core classes and set up a custom the EntityManager)
2. Install a Package which contains the match_against Doctrine Lexer

Since I already have a running website with concrete5 v5.7.5.6 and a match_against Lexer in place, I can provide you with some example code, if you like. I only would recommend this approach for big projects, which contain many custom entities and require a single EntityManagaer

**Alternative solution**
Please also consider the following option (I would prefer this approach, for small websites):

1. Just use a native query. Here is an example of mine

```php
            // Class ArticleRepository

            $connection = $this->getEntityManager()->getConnection();
            // Or use $this->em = \ORM::entityManager(); 

            // mysql excapeing
            // http://stackoverflow.com/questions/14926386/how-to-search-for-slash-in-mysql-and-why-escaping-not-required-for-wher
            $sql = "SELECT foreign_key
                    FROM ext_translations as trans
                    LEFT JOIN mbtarticles AS a
                    ON a.id = trans.foreign_key
                    AND trans.locale = :language
                    AND object_class = 'Application\\\\Src\\\\Product\\\\Model\\\\Entity\\\\Article'
                    WHERE
                    MATCH(content) AGAINST (:searchQuery IN BOOLEAN MODE) > 0
                    OR MATCH(a.articleNumber, a.name, a.searchKeywords) AGAINST (:searchQuery IN boolean MODE) > 0
                    GROUP BY trans.foreign_key";

            $statement = $connection->prepare($sql);
            $params = array(
                'language' => $language,
                'searchQuery' => $searchString
            );

            $statement->execute($params);
            $articleIdsRaw = $statement->fetchAll();
```

**Comment by tkart38** [comment]
hi Kaapii,
thanks for your answer! 
I explain you my situation  
I've a big site with over 160.000 article and need to speed up the query.
I can't use the native query because it means rewrite all the pagelist query. 
For this reason i need to add MATCH_AGAINST extension for doctrine.
i've follow this guide http://ourcodeworld.com/articles/read/90/how-to-implement-fulltext-search-mysql-with-doctrine-and-symfony-3 but the problem is add it on concrete5, if you can tell me how can do that i really appreciate!!

how can i check if concrete5 only runs with one EntityManager instance? 
thanks in advance for you help and time 
bye

**Comment by Kaapiii** [comment]
I see. So you find the relevant code portions here: [Link](https://gist.github.com/Kaapiii/1d681cde297563d9c426f2366beb4c4b)

Note: If your concrete version doesn't match the specified version (5.7.5.6), you may have to override or extends other core classes.

In order to create a customized EntityManager you have to override 3 core classes:
1. Register the overriding of the DatabaseServiceProvider in the application/config folder
2. Replace the line 20 in the DatabaseServiceProvider with "$this->app->bind('database/orm', '\Application\Src\Database\DatabaseManagerORM');"
3. Override the DatabaseManagerORM class according to the gist
4. Create the EntityManager according to the gist. If you don't need the Gedmo stuff, you can remove the code.
6. Install the "doctrine_dql_extensions" package which contains the match against functionality. You find the plugin for concrete version 5.7.5.6 [here](https://github.com/Kaapiii/doctrine_dql_extensions).

**Comment by tkart38** [comment]
hi 
thanks for your help
i don't know if the problem is the concrete version ( 5.7.5.8) but i receive this error that require the environments.php file and i don'know if i need this file .and what i've to put in this file.
Application\Src\Database\EntityManagerFactory::create(): Failed opening required '/var/www/vhosts/mysite.com/application/bootstrap/environments.php' (include_path='/var/www/vhosts/mysite.com/concrete/vendor:.:/usr/share/php:/usr/share/pear') 

any ideas?

**Comment by tkart38** [comment]
no my error i solve this error
i've problem using this

$query->andWhere("MATCH_AGAINST (ak_blog_category, :searchterm 'IN BOOLEAN MODE') > 0.0");
$query->setParameter('searchterm','Calciomercato');
receive 
SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION collaudo_gdm.MATCH_AGAINST does not exist 
there are sonthing wrong on my sintaxt?

**Comment by Kaapiii** [comment]
It's a way of checking the running environment. If you're developing locally, you don't want doctrine to cache anything. (Doctrine will use the ArrayCache). As soon as you deploy, the default concrete5 cache will be used.

Just add under **'application/bootstrap/'** an **environments.php** file, with the following content.
Replace "PC3" with the name of your computer, and you should be good to go. 

![image](https://user-images.githubusercontent.com/995643/26979249-6b3955e2-4d2e-11e7-85ba-57e284ebc2de.png)

**Comment by Kaapiii** [comment]
Probably. For debugging, try to output the entire query, and run the query in a database tool (MySQL workbench). I guess it's just a missing white space: **"collaudo_gdm.MATCH_AGAINST"** this should probably be something like **"collaudo_gdm MATCH_AGAINST"**

```php
$query->getSQL();
```

**Comment by tkart38** [comment]
sorry but i'dont know if i'm using the pakage with the match_against extension.
i've put a die() on MatchAgainst.php in the package but nothing appends.

now i've with doctrine i use this 
$query->andWhere("MATCH_AGAINST(ak_blog_category :searchterm )> 0.0");
$query->setParameter('searchterm','Calciomercato');

and this is the sql  

SELECT p.cID FROM WHERE (ak_is_canonical_page < 1) AND (cv.cvDatePublic <= :dcValue1) AND (cvName != :dcValue2) AND ((ak_exclude_page_list = 0 or ak_exclude_page_list is null)) AND ((pp.cPath LIKE :pbFilterByPath AND pp.cPath <> :pbFilterByPath2)) AND (MATCH_AGAINST(ak_blog_category :searchterm )> 0.0) ORDER BY cv.cvDatePublic desc LIMIT 10_

but receive this error:

SQLSTATE[42000]: Syntax error or access violation: 1584 Incorrect parameters in the call to stored function 'MATCH_AGAINST' 

it's seams that the doctrine dql extension pakage doesn't "start".
how can' i check it?

thanks for your time and help.
sorry but is de first time i work with doctrine extension.

**Comment by Kaapiii** [comment]
1. It seems that there is missing a table in the query (between FROM and WHERE):
```mysql
SELECT p.cID FROM
  collectionversions 
  WHERE (ak_is_canonical_page < 1) 
  AND (cv.cvDatePublic <= :dcValue1) 
  AND (cvName != :dcValue2) 
  AND ((ak_exclude_page_list = 0 or ak_exclude_page_list is null)) 
  AND ((pp.cPath LIKE :pbFilterByPath AND pp.cPath <> :pbFilterByPath2)) 
  AND (match(ak_blog_category) against ('test' IN BOOLEAN MODE)> 0) 
  ORDER BY cv.cvDatePublic desc LIMIT 10
```
2. Did you instal the package correctly? 
- copy the folder **doctrine_dql_extensions" to packages/ folder
- Install the package under "Extend concrete5" -&gt; "Add functionality"
- Then the MATCH_AGAINST() dql string should be converted automatically to mysql

**Comment by Kaapiii** [comment]
@tkart38 

Here is a example how i use it:

```php

    $searchString = 'test';

    $dql = "SELECT a FROM \Application\Src\Product\Model\Entity\Article a "
        ."WHERE a.active = true "
        . "AND a.public = true "
        . "AND MATCH_AGAINST(a.articleNumber, a.name, a.searchKeywords, :searchString 'IN BOOLEAN MODE') > 0";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('searchString', $searchString);
        $results = $query->getResult();
```

**Comment by tkart38** [comment]
Hi i ve reinstalled  the package some time, i'll check if there are problem
with the installation process and test the dql alone.
Thanks Again

Il 09 Giu 2017 20:04, "Markus Liechti" <notifications@github.com> ha
scritto:
